name: test ci

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm start
